blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    #根据设计需求， 总共有6个页面要实现
    path('', views.index, name='index'),#网站首页
    path('blog/', views.blog, name='blog'),
    path('diary/', views.diary, name= 'diary'),
    path('inspiration/',views.inspiration, name="inspiration"),
    path('list-<int:lid>.html', views.list, name='list'),  # 分类列表页
    path('show-<int:sid>.html', views.show, name='show'),  # 内容页
    path('tag/<tag>', views.tag, name='tag'),  # 标签列表页
    path('s/', views.search, name='search'),  # 搜索列表页
    path('about/', views.about, name='about'),  # 联系我们单页
]

comment/urls.py
from django.conf.urls import url
from django.urls import path
from comment import views

app_name = 'comment'
urlpatterns = [
    path('upload_comment/', views.upload_comment, name="upload_comment"),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),  #登录页面
    path('register/', views.register, name='register'), #注册页面
    path('logout/',views.logout, name='logout'), #登出
    path('user_info/', views.user_info, name='user_info'), #用户信息
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
from django.contrib.contenttypes.fields import GenericRelation
from read_no_count.models import ReadNumExpandMethod,ReadDetail

# Create your models here.

class Category(models.Model):
    name = models.CharField('博客分类', max_length=100)
    index = models.IntegerField(default=1, verbose_name='分类')
    excerpt = models.TextField('摘要', max_length=200, blank=True,null=True)
    img = models.ImageField(upload_to='category_img/%Y/%m/%d/', verbose_name='首页分类图片', blank=True, null=True)

    class Meta:
        #这是后台admin会显示的名字
        verbose_name = '博客分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=100)
    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#推荐位
class Tui(models.Model):
    name = models.CharField('推荐位',max_length=100)

    class Meta:
        verbose_name = '推荐位'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#文章
#继承了类ReadNumExpanMethod内的方法views,才可以在后台的 文章 内显示浏览数！
class Article(models.Model, ReadNumExpandMethod):
    title = models.CharField('标题', max_length=70)
    excerpt = models.TextField('摘要', max_length=200, blank=True)
    #使用外键关联分类表与分类是一对多关系，可以为blank
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='分类', blank=True)
    #使用外键关联标签表与标签是多对多关系
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)


    img = models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片   ',blank=True,null=True)
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    # body = models.TextField()     #通过以下富文本编辑器(百度的)来更好的添加文本
    content = UEditorField('内容', width=800, height=700,toolbars='full', imagePath='upimg/',filePath='upfile/',
                        upload_settings={'imageMaxSize': 1204000},
                        settings={}, command=None, blank=True)
    """
        留意里面的imagePath="upimg/", filePath="upfile/" 这两个是图片和文件上传的路径，
        我们上传文件，会自动上传到项目根目录media文件夹下对应的upimg和upfile目录里，
        这个目录名可以自行定义。有的人问，为什么会上传到media目录里去呢？那是因为之前我们在基础配置文章里，
        设置了上传文件目录media。
    """

    #外键，文章作者关联用户模型，系统自带的
    """
         文章作者，这里User是从django.contrib.auth.models导入的。
         专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
         这里我们通过 ForeignKey 把文章和 User 关联了起来。
         因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    """
    auther = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')


    tui = models.ForeignKey(Tui, on_delete=models.DO_NOTHING, verbose_name='推荐位', blank=True, null=True)

    created_time = models.DateTimeField('发布时间', auto_now_add=True)  #创建时间，用来标识这条记录的创建时间，具有auto_now_add属性，创建记录时会自动填充当前时间到此字段
    modified_time = models.DateTimeField('修改时间', auto_now=True)     #修改时间，用来标识这条记录最后一次的修改时间，具有auto_now属性，当记录发生变化时填充当前时间到此字段

    # 通过GenericRelation来跟另外一个app内的模型model建立关系！
    read_details = GenericRelation(ReadDetail)



    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Article, Category, Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from read_no_count.utils import read_no_count_once_read, get_seven_days_read_data,get_allTime_hot_data

# Create your views here.

# 右侧aside栏
# def global_variable(request):
#     # 置顶推荐
#     tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3] #拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
#     #热门十篇文章
#     hot = Article.objects.all().order_by('views')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
#     # 文章分类
#     allcategory = Category.objects.all()
#     # 文章标签
#     tags = Tag.objects.all()
#     return locals()


# 首页
def index(request):
    allcategory = Category.objects.filter(index=1).order_by("-id")[0:3]
    allarticle = Article.objects.all().order_by('-id')[0:3]

    dates, read_nums = get_seven_days_read_data(Article)  #用来统计过去七天每天的流量

    return render(request, 'index.html', locals())



def blog(request):
    exclude_list = ['日记','感悟']
    Allarticle = Article.objects.exclude(category__name__in=exclude_list).order_by('-id')  # ---最新文章：中间10篇文章
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()# 文章分类
    tags = Tag.objects.all()# 文章标签

    hot = get_allTime_hot_data(Article)  #返回一堆QuerySet【<ReadNum: ReadNum object (1)>, <ReadNum: ReadNum object (2)>。。。等， 就是后台--浏览--模型内的所有！1】


    page =request.GET.get("page")  #在网址中获取page的参数值
    paginator = Paginator(Allarticle,10)   #10篇翻一页
    try:
        allarticle = paginator.page(page)   # 获取当前页码的记录
    except PageNotAnInteger:
        allarticle = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        allarticle = paginator.page(paginator.num_pages) # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'blog.html', locals())



def list(request, lid):
    List = Article.objects.filter(category_id=lid).order_by('-id') # 获取通过URL传进来的lid，然后筛选出对应分类id的文章
    category_name = Category.objects.get(id=lid) # 获取当前文章的分类名
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签


    hot = get_allTime_hot_data(Article)



    page = request.GET.get('page')  # 在网址URL中获取当前页面数
    paginator = Paginator(List, 10)  # 对查询到的数据对象list进行分页，设置超过5条数据就分页
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'list.html', locals())



def show(request, sid):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签
    interestTopic = Article.objects.all().order_by('?')[0:5]  # 内容下面的您可能感兴趣的文章，随机推荐
    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    show = Article.objects.get(id=sid)  # 查询指定ID的文章-----找到对应内容的文章
    previous_blog = Article.objects.filter(created_time__gt=show.created_time,
                                           category=show.category.id).first()  # create time大于本文的定义为上一篇
    netx_blog = Article.objects.filter(created_time__lt=show.created_time,
                                       category=show.category.id).last()  # 小于本文的定义为下一篇。  category=show.category.id，则是指定查询的文章为  当前分类下  的文章。

    #阅读量方法函数的引入和使用
    read_coockie_key = read_no_count_once_read(request,show)  #这返回的是一个key， 计算文章的总阅读量

    response = render(request, 'show.html',locals())
    response.set_cookie(read_coockie_key,'true')
    return response



def tag(request, tag):
    List = Article.objects.filter(tags__name=tag).order_by('-id') # 通过文章标签进行查询文章--提取对应tag的文章
    tag_name = Tag.objects.get(name=tag) # 返回当前搜索的标签的标签名
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签

    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    page = request.GET.get('page')
    # tags = Tag.objects.all()
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'tag.html', locals())



def search(request):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    # hot = Article.objects.all().order_by('-views()')[0:10]  # 通过浏览数进行排序， 提取出热门文章---右侧热门10篇文章排行
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签

    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)


    ss = request.GET.get('search')  # 获取搜索的关键词
    List = Article.objects.filter(title__icontains=ss).order_by('-created_time')  # 获取到搜索关键词通过标题进行匹配---找到对应的搜索文章

    page = request.GET.get('page')
    # tags = Tag.objects.all()
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容

    return render(request, 'search.html',locals())



def inspiration(request):
    tui = Article.objects.filter(tui__id=1).order_by("-id")[0:3]  # 拿推荐位id为1的3篇文章， 所以后台要设置 置顶推荐 的tui的id = 1
    allcategory = Category.objects.all()  # 文章分类
    tags = Tag.objects.all()  # 文章标签
    # 右侧热门文章的逻辑(历史累计热门)
    hot = get_allTime_hot_data(Article)

    List = Article.objects.filter(category__name='感悟').order_by('-id')

    page = request.GET.get('page')
    paginator = Paginator(List, 10)
    try:
        list = paginator.page(page)  # 获取当前页码的记录
    except PageNotAnInteger:
        list = paginator.page(1)  # 如果用户输入的页码不是整数时,显示第1页的内容
    except EmptyPage:
        list = paginator.page(paginator.num_pages)  # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
    return render(request, 'inspiration.html',locals())



def about(request):
    return render(request, 'about.html',locals())


def diary(request):
    list = Article.objects.filter(category__name='日记').order_by('-created_time')
    dates = Article.objects.filter(category__name='日记').datetimes('created_time', 'year', order='DESC')

    # 下面两条如果用日和月归档的话，才用得上
    date = Article.objects.filter(category__name='日记').datetimes('created_time', 'month', order='DESC')
    dat = Article.objects.filter(category__name='日记').datetimes('created_time', 'day', order='DESC')


    return render(request, 'diary.html', locals())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="Author" content="禾斗">
    <meta name="robots" content="all" />


	<title>禾斗的小博客</title>
	<meta name="description" content="这是禾斗的博客啊" />
	<meta name="keywords" content="技术，博客，知识分享，互联网，前端，后端，网站" />

    <link rel="stylesheet" href="{% static "css/bootstrapv3.3.7.min.css" %}" />
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "layui/css/layui.css" %}" />
    <link rel="stylesheet" href="{% static "css/master.css" %}" />
    <link rel="stylesheet" href="{% static "css/gloable.css" %}" />
    <link rel="stylesheet" href="{% static "css/nprogress.css" %}" />

    <link rel="stylesheet" href="{% static "css/blog.css" %}" />


    {% block head %}
    {% endblock %}
</head>



<body>
<!--header-->
    <div class="header">
    </div>
    <header class="gird-header">
        <div class="header-fixed">
            <div class="header-inner">
                <a href="/" class="header-logo" id="logo">
                    <img class="myicon" src='{% static "images/icon.jpg" %}' alt="头像">
                    <img class="mylogo" src='{% static "images/mine.png" %}' alt="禾斗的博客的logo">
                </a>
                <nav class="nav" id="nav">
                    <ul>
                        <li><a href="/">首页</a></li>
                        <li><a href="/blog/">个人博客</a></li>
                        <li><a href="/inspiration/">感悟</a></li>
                        <li><a href="/diary/">日记</a></li>
                        <li><a href="/about/">关于</a></li>
                        <li>
                            <form method="get" action="{% url 'blog:search' %}">
                                <input type="search" name="search" placeholder="Search">
                            </form>
                        </li>
                    </ul>
                </nav>



            <!--登录注册-->
                <div>
                    <ul class="navbar-nav navbar-right login-left" style="position: absolute; right: -286px;top: 0">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登录</a></li>
                            <li class="reg-ignore"><a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a></li>
                        {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ user.username }} <span class="caret"></span></a>
                                <ul class="dropdown-menu login-line">
                                    <li><a href="{% url 'user:user_info' %}">个人资料</a></li>
                                    <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">退出</a></li>
                               </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>

                <a class="phone-menu">
                    <i></i>
                    <i></i>
                    <i></i>
                </a>
            </div>
        </div>
    </header>
<!--header END-->




    {% block content %}


    {% endblock %}






    <footer class="grid-footer">
        <div class="footer-fixed">
            <div class="copyright">
                <div class="info">
                    <div class="contact">
                        <a href="https://github.com/ChanForWang" class="github" target="_blank"><i class="fa fa-github"></i></a>
{#                        <a href="https://wpa.qq.com/msgrd?v=3&uin=930054439&site=qq&menu=yes" class="qq" target="_blank" title="930054439"><i class="fa fa-qq"></i></a>#}
                        <a href="https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=gbiysbG0tbWyuMHw8K-i7uw" class="email" target="_blank" title="930054439@qq.com"><i class="fa fa-envelope"></i></a>
                        <a href="javascript:void(0)" class="weixin"><i class="fa fa-weixin"></i></a>
                    </div>
                    <p class="mt05">
                        Copyright &copy; 2020-2020 禾斗 All Rights Reserved V.1.0.0
                    </p>
                </div>
            </div>
        </div>
    </footer>





    <script type="text/javascript" src="{% static "layui/layui.js" %}"></script>
    <script type="text/javascript" src="{% static "js/yss/gloable.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/nprogress.js" %}"></script>
    <script>NProgress.start();</script>
 	<script type="text/javascript" src="{% static "js/yss/article.js" %}"></script>


    <!--一定要放在这后面, 不然手机模式下的右侧栏会失效-->
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script type="text/javascript" src="{% static "js/bootstrapv3.3.7.min.js" %}"></script>


    {% block script_extends %}
    {% endblock %}


    {% block script_funtion_extens %}
    {% endblock %}

    <script>
        /*顶部加载条*/
        window.onload = function () {
            NProgress.done();
        };
    </script>






</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% block content %}

<div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);color: #00a0e9; font-size: 3em">
    {{ message }}, <a href="{{ redirect_to }}">返回</a>
</div>

{% endblock %}

templates/inspiration.html
{% extends "base.html" %}
{% load comment_tags %}
{% block content %}



    <div class="doc-container" id="doc-container">
        <div class="container-fixed">
		    <div class="col-content">
		        <div class="inner">
		            <article class="article-list bloglist" id="LAY_bloglist" >
                        {% for li in list %}


                            {% if forloop.counter == 1 %}
                            <div class="breadcrumb" style="margin-top: 1rem">
                                您的位置： <a itemprop="breadcrumb" href="/" style="color: #00a0e9">首页</a> » <span class="current">感悟</span>
                            </div>
                            {% endif %}

						<section class="article-item zoomIn article">

                            {% if forloop.counter == 1 %}
                            <div class="main-title">
                                <h4 class="post-left-title">感悟 <span style="color:rgb(65, 117, 214)">2020</span><span style="margin-left: 0.5rem">(Total:{{ List|length }}篇)</span></h4>
                            </div>
							<div class="fc-flag">头条</div>
                            {% endif %}


							<h5 class="title">       
								<span class="fc-blue">【原创】</span>       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html">{{ li.title }}</a>
							</h5>   
							<div class="time">       
								<span class="day">{{ li.created_time|date:"d" }}</span>
								<span class="month fs-18">{{ li.created_time|date:"m" }}<span class="fs-14">月</span></span>
								<span class="year fs-18 ml10">{{ li.created_time|date:"Y" }}</span>
							</div>   
							<div class="content">       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="cover img-light">
									<img href="/media/{{ li.img }}" srcset="/media/{{ li.img }}" alt="{{ li.title}}"/>
								</a>
								<p style="font-size: 1.3rem">{{ li.excerpt|truncatechars:"100" }}</p>
							</div>   
							<div class="read-more">       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="fc-black f-fwb">继续阅读</a>
							</div>    
							<aside class="f-oh footer">       
								<div class="f-fl tags">           
									<span class="fa fa-tags fs-16"></span>           
									<a class="tag" href="{% url "blog:index" %}list-{{ li.category_id }}.html">{{ li.category.name }}</a>
								</div>       
								<div class="f-fr">           
									<span class="read">               
										<i class="fa fa-eye fs-16"></i>               
										<i class="num">{{ li.views }}</i>
									</span>
									<span class="ml20">               
										<i class="fa fa-comments fs-16"></i>               
										<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="num fc-grey">{% get_comment_count li %}</a>
									</span>       
								</div>   
							</aside>
						</section>

                        {% endfor %}

		            </article>
		        </div>
		    </div>



            <!--=========底部分页！-->
            <div class="pagination">
                <ul>
                    {% if list.has_previous %}
                        <li class="prev-page"><a href="?page={{ list.previous_page_number }}">上一页</a></li>
                    {% else %}
                        <li class="prev-page"></li>
                    {% endif %}

                     {% for num in list.paginator.page_range %}
                        {% if num %}
                            {% ifequal num list.number %}
                                 <li class="active"><span>{{ num }}</span></li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="disabled"><span>...</span></li>
                        {% endif %}
                     {% endfor %}

                    {% if list.has_next %}
                        <li class="next-page"><a href="?page={{ list.next_page_number }}">下一页</a></li>
                    {% else %}
                        <li class="prev-page"></li>
                    {% endif %}

                </ul>
            </div>

            <!--=========右侧共有导航栏！-->
		    {% include "right.html" %}

		</div>
    </div>

{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load comment_tags %}

{% block content %}



    <div class="doc-container" id="doc-container">
        <div class="container-fixed">
		    <div class="col-content">
		        <div class="inner">
		            <article class="article-list bloglist" id="LAY_bloglist" >
                        {% for li in list %}


                            {% if forloop.counter == 1 %}
                            <div class="breadcrumb" style="margin-top: 1rem">
                                您的位置： <a itemprop="breadcrumb" href="/" style="color: #00a0e9">首页</a> » <span class="current">{{ category_name }}</span>
                            </div>
                            {% endif %}

						<section class="article-item zoomIn article">

                            {% if forloop.counter == 1 %}
                            <div class="main-title">
                                <h4 class="post-left-title">分类：{{ category_name }}<span style="margin-left: 0.5rem">(Total:{{ List|length }}篇)</span></h4>
                            </div>
							<div class="fc-flag">头条</div>
                            {% endif %}


							<h5 class="title">       
								<span class="fc-blue">【原创】</span>       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html">{{ li.title }}</a>
							</h5>   
							<div class="time">       
								<span class="day">{{ li.created_time|date:"d" }}</span>
								<span class="month fs-18">{{ li.created_time|date:"m" }}<span class="fs-14">月</span></span>
								<span class="year fs-18 ml10">{{ li.created_time|date:"Y" }}</span>
							</div>   
							<div class="content">       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="cover img-light">
									<img href="/media/{{ li.img }}" srcset="/media/{{ li.img }}" alt="{{ li.title}}"/>
								</a>
								<p style="font-size: 1.3rem">{{ li.excerpt|truncatechars:"100" }}</p>
							</div>   
							<div class="read-more">       
								<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="fc-black f-fwb">继续阅读</a>
							</div>    
							<aside class="f-oh footer">       
								<div class="f-fl tags">           
									<span class="fa fa-tags fs-16"></span>           
									<a class="tag" href="{% url "blog:index" %}list-{{ li.category_id }}.html">{{ li.category.name }}</a>
								</div>       
								<div class="f-fr">           
									<span class="read">               
										<i class="fa fa-eye fs-16"></i>               
										<i class="num">{{ li.views }}</i>
									</span>
									<span class="ml20">               
										<i class="fa fa-comments fs-16"></i>               
										<a href="{% url 'blog:index' %}show-{{ li.id }}.html" class="num fc-grey">{% get_comment_count li %}</a>
									</span>       
								</div>   
							</aside>
						</section>

                        {% endfor %}

		            </article>
		        </div>
		    </div>



            <!--=========底部分页！-->
            <div class="pagination">
                <ul>
                    {% if list.has_previous %}
                        <li class="prev-page"><a href="?page={{ list.previous_page_number }}">上一页</a></li>
                    {% else %}
                        <li class="prev-page"></li>
                    {% endif %}

                     {% for num in list.paginator.page_range %}
                        {% if num %}
                            {% ifequal num list.number %}
                                 <li class="active"><span>{{ num }}</span></li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="disabled"><span>...</span></li>
                        {% endif %}
                     {% endfor %}

                    {% if list.has_next %}
                        <li class="next-page"><a href="?page={{ list.next_page_number }}">下一页</a></li>
                    {% else %}
                        <li class="prev-page"></li>
                    {% endif %}

                </ul>
            </div>

            <!--=========右侧共有导航栏！-->
		    {% include "right.html" %}

		</div>
    </div>

{% endblock %}

templates/register.html
 {% extends "base.html" %}

{% block head %}
    <style>
        @media screen and (max-width: 1024px){
            form.layui-form{position: absolute!important;left: 50% !important}
        }
    </style>
{% endblock %}
{% block content %}

    <div style="height:300px; margin-top: 250px;margin-bottom: 292px; padding: 30px; padding-top: 108px; border-radius: 30px">
        <form class="layui-form" method="POST" action=" " style="position: absolute;top: 50%;left: 50%;transform: translate(-50%,-50%);background-color: white;padding: 10px 30px;border-radius: 20px;">
            {% csrf_token %}
            <div class="layui-form-item"style="margin-top: 20px">
                {% for field in reg_form %}
                <label for="{{ field.id_for_label }}" >{{ field.label }}</label>
                <div class="layui-input-block" style="margin-left: 0;">
                    {{ field }}
                    <p class="text-danger">{{ field.errors.as_text }}</p>
                </div>
                {% endfor %}
                <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                <input type="submit" value="注册" class="layui-btn layui-btn-normal pull-right" style="margin-top: 20px;border-radius: 20px">
            </div>

        </form>
    </div>


{% endblock %}